/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type $Read<T> = {
    readonly $read: T;
};
export type $Write<T> = {
    readonly $write: T;
};
export type Readable<T> = T extends $Write<any> ? never : T extends $Read<infer U> ? Readable<U> : T extends (infer E)[] ? Readable<E>[] : T extends object ? {
    [K in keyof T as NonNullable<T[K]> extends $Write<any> ? never : K]: Readable<T[K]>;
} : T;
export type Writable<T> = T extends $Read<any> ? never : T extends $Write<infer U> ? Writable<U> : T extends (infer E)[] ? Writable<E>[] : T extends object ? {
    [K in keyof T as NonNullable<T[K]> extends $Read<any> ? never : K]: Writable<T[K]>;
} & {
    [K in keyof T as NonNullable<T[K]> extends $Read<any> ? K : never]?: never;
} : T;
export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** (M14-IF-010)配車依頼 */
        post: operations["postOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/by/order-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** (M14-IF-020)配車情報複数取得 */
        get: operations["getOrdersByOrderId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/by/order-id/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** (M14-IF-030)配車情報単一取得 */
        get: operations["getOrderByOrderId"];
        put?: never;
        post?: never;
        /** (M14-IF-040)配車依頼キャンセル */
        delete: operations["deleteOrderByOrderId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description リクエスター側 配車依頼ユニークID<br/>- t_order.requester_order_id */
        orderId: string;
        Order: {
            /**
             * @description 共同配車システム 配車依頼ユニークID<br/>- t_order.order_id
             * @example 1
             */
            id?: $Read<number>;
            /**
             * @description リクエスター側 配車依頼ユニークID<br/>- t_order.requester_order_id
             * @example 123456789
             */
            order_id?: $Write<string>;
            /**
             * @description 共同配車システム タクシー事業者ID<br/>- t_order.company_id
             * @example 1
             */
            company_id: $Write<number>;
            /**
             * @description 顧客 電話番号<br/>- t_order.phone_number
             * @example 08012345678
             */
            phone_number: $Write<string>;
            /**
             * @description 顧客 メールアドレス(※)
             *
             *     (※)配車結果の通知先メールアドレス。送信したいメールの種類はAPIではなくサーバ側で設定可（要設定依頼）。
             *     - 即時配車受領: タクシーを手配しました
             *     - 即時配車拒否: 配車リクエストを受け付けることができませんでした
             *     - 予約受付: タクシー予約が確定しました
             *     - 予約拒否: 予約が成立しませんでした
             *     - 予約キャンセル: タクシー予約をキャンセルしました
             *     <br/>- t_order.email
             * @example example@example.com
             */
            email?: $Write<string>;
            /**
             * @description 顧客名<br/>- t_order.passenger_name
             * @example 顧客太郎
             */
            passenger_name?: $Write<string>;
            /**
             * @description 顧客名 読み<br/>- t_order.passenger_name_yomi
             * @example こきゃくたろう
             */
            passenger_name_yomi?: $Write<string>;
            /**
             * @description 迎車地点名<br/>- t_order.location_name
             * @example 徳島駅
             */
            location_name?: $Write<string>;
            /**
             * @description 迎車地点 住所<br/>- t_order.location_address
             * @example 徳島県徳島市寺島本町西1−６１
             */
            location_address?: $Write<string>;
            /**
             * Format: float
             * @description 迎車地点 緯度（世界測地系 WGS84）<br/>- t_order.location_lat
             * @example 34.0742
             */
            location_lat: $Write<number>;
            /**
             * Format: float
             * @description 迎車地点 経度（世界測地系 WGS84）<br/>- t_order.location_lng
             * @example 134.551268
             */
            location_lng: $Write<number>;
            /**
             * @description 降車地点名<br/>- t_order.destination_name
             * @example 大塚製薬
             */
            destination_name?: $Write<string>;
            /**
             * @description 降車地点 住所<br/>- t_order.destination_address
             * @example 徳島県鳴門市撫養町大桑島濘岩浜
             */
            destination_address?: $Write<string>;
            /**
             * Format: float
             * @description 降車地点 緯度（世界測地系 WGS84）<br/>- t_order.destination_lat
             * @example 34.0742
             */
            destination_lat?: $Write<number>;
            /**
             * Format: float
             * @description 降車地点 経度（世界測地系 WGS84）<br/>- t_order.destination_lng
             * @example 134.551268
             */
            destination_lng?: $Write<number>;
            /**
             * Format: date-time
             * @description 予約日時 （指定がある場合は予約として扱われ、指定がない場合は即時配車となる）<br/>- t_order.reserve_at
             * @example 2023-01-30T08:30:00+09:00
             */
            reserve_at?: $Write<string>;
            /**
             * Format: date-time
             * @description 乗車希望時間<br/>- t_order.requested_pickup_at
             * @example 2030-12-30T08:30:00+09:00
             */
            requested_pickup_at?: $Write<string>;
            /**
             * @description 配車詳細情報<br/>- t_order.message
             * @example 介護タクシー希望
             */
            message?: $Write<string>;
            /**
             * @description アプリ内決済を利用するかどうか。指定ない場合はfalse<br/>- t_order.in_app_payment
             * @example false
             */
            in_app_payment?: $Write<boolean>;
            /**
             * @description 決済 ユニークID<br/>- t_payment.payment_id
             * @example 1
             */
            payment_id?: $Read<number>;
            /**
             * @description 決済ステータス
             *       pending: 待機中
             *       in-progress: 進行中
             *       succeed: 成功
             *       failed: 失敗
             *       canceled: キャンセル
             *     <br/>- t_payment.payment_status
             * @example pending
             */
            payment_status?: $Read<string>;
        };
        DeleteOrder: {
            /**
             * @description 共同配車システム 配車依頼ユニークID<br/>- t_order.order_id
             * @example 1
             */
            id?: $Read<number>;
        };
        GetOrder: {
            /**
             * @description 共同配車システム 配車依頼ユニークID<br/>- t_order.order_id
             * @example 1
             */
            id?: $Read<number>;
            /**
             * @description リクエスター 配車依頼ユニークID(配車依頼作成時に指定がなかった場合は共同配車システム側で自動生成されたものを返却)<br/>- t_order.requester_order_id
             * @example 82YVIU9tXVmTmlLSwQ==
             */
            order_id?: $Read<string>;
            /**
             * @description 迎車地点名<br/>- t_order.location_name
             * @example 徳島駅
             */
            location_name?: $Read<string>;
            /**
             * @description 迎車地点 住所<br/>- t_order.location_address
             * @example 徳島県徳島市寺島本町西1−６１
             */
            location_address?: $Read<string>;
            /**
             * Format: float
             * @description 迎車地点 緯度<br/>- t_order.location_lat
             * @example 34.0742
             */
            location_lat?: $Read<number>;
            /**
             * Format: float
             * @description 迎車地点 経度<br/>- t_order.location_lng
             * @example 134.551268
             */
            location_lng?: $Read<number>;
            /**
             * @description 降車地点名(降車地点を指定した場合のみ有効)<br/>- t_order.destination_name
             * @example 大塚製薬
             */
            destination_name?: $Read<string>;
            /**
             * @description 降車地点 住所(降車地点を指定した場合のみ有効)<br/>- t_order.destination_address
             * @example 徳島県鳴門市撫養町大桑島濘岩浜
             */
            destination_address?: $Read<string>;
            /**
             * Format: float
             * @description 降車地点 緯度(降車地点を指定した場合のみ有効)<br/>- t_order.destination_lat
             * @example 34.0742
             */
            destination_lat?: $Read<number>;
            /**
             * Format: float
             * @description 降車地点 経度(降車地点を指定した場合のみ有効)<br/>- t_order.destination_lng
             * @example 134.551268
             */
            destination_lng?: $Read<number>;
            /**
             * @description 配車詳細情報<br/>- t_order.message
             * @example 介護タクシー希望
             */
            message?: $Read<string>;
            /**
             * Format: date-time
             * @description 更新日時<br/>- t_order.updated_at
             * @example 2021-12-30T08:30:00+09:00
             */
            updated_at?: $Read<string>;
            /**
             * @description 配車ステータス
             *       01: 未配車
             *       02: 振替中
             *       03: 迎車中
             *       04: 到着
             *       05: 実車中
             *       06: 予約確定
             *       07: 事業者キャンセル
             *       08: 顧客キャンセル
             *       09: 降車
             *     <br/>- t_order.order_status
             * @example 01
             * @enum {string}
             */
            order_status?: $Read<"01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09">;
            /**
             * Format: date-time
             * @description 到着時刻(order_status = 03の時のみ有効)<br/>- t_order.arrival_time
             * @example 2023-01-30T08:30:00+09:00
             */
            arrival_time?: $Read<string>;
            /**
             * Format: date-time
             * @description 降車時刻(order_status = 03 or 05の時のみ有効)<br/>- t_order.dropoff_time
             * @example 2023-12-30T08:30:00+09:00
             */
            dropoff_time?: $Read<string>;
            /**
             * @description 乗務員名(order_status = 03の時のみ有効)<br/>- t_crew_assign.crew_name
             * @example 顧客太郎
             */
            crew_name?: $Read<string>;
            /**
             * @description 乗務員 無線番号(order_status = 03の時のみ有効)<br/>- t_crew_assign.crew_number
             * @example 1234
             */
            crew_number?: $Read<string>;
            /**
             * @description 乗務員 車両番号(order_status = 03の時のみ有効)<br/>- t_crew_assign.crew_plate_number
             * @example 1234
             */
            crew_plate_number?: $Read<string>;
            /**
             * Format: float
             * @description 乗務員 現在地 緯度(order_status = 03の時のみ有効)<br/>- t_crew_current_location.crew_lat
             * @example 34.0742
             */
            crew_lat?: $Read<number>;
            /**
             * Format: float
             * @description 乗務員 現在地 経度(order_status = 03の時のみ有効)<br/>- t_crew_current_location.crew_lng
             * @example 134.551268
             */
            crew_lng?: $Read<number>;
            /**
             * Format: float
             * @description 乗務員 向き(order_status = 03の時のみ有効)<br/>- t_crew_current_location.degree
             */
            degree?: $Read<number>;
            /**
             * @description タクシー事業者ID<br/>- t_order.company_id
             * @example 1
             */
            company_id?: $Read<number>;
            /**
             * @description タクシー事業所名<br/>- m_company.company_name
             * @example 吉野川タクシー
             */
            company_name?: $Read<string>;
            /**
             * @description タクシー事業者連絡先<br/>- m_company.contact
             * @example 0120-999-999
             */
            contact?: $Read<string>;
            /**
             * Format: date-time
             * @description 予約日時(予約作成完了後のみ有効)<br/>- t_order.reserve_at
             * @example 2021-12-30T08:30:00+09:00
             */
            reserve_at?: $Read<string>;
            /**
             * @description 決済 ユニークID<br/>- t_payment.payment_id
             * @example 1
             */
            payment_id?: $Read<number>;
            /**
             * @description 決済ステータス
             *       pending: 待機中
             *       in-progress: 進行中
             *       succeed: 成功
             *       failed: 失敗
             *       canceled: キャンセル
             *     <br/>- t_payment.payment_status
             * @example pending
             * @enum {string}
             */
            payment_status?: $Read<"pending" | "in-progress" | "succeed" | "failed" | "canceled">;
        };
    };
    responses: {
        /** @description BadRequest */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description UnAuthorized */
        "401UnAuthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description NotFound */
        "404NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description Conflict */
        "409Conflict": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
        /** @description InternalServerError */
        "500InternalServerError": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    message?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401UnAuthorized"];
            404: components["responses"]["404NotFound"];
            409: components["responses"]["409Conflict"];
            500: components["responses"]["500InternalServerError"];
        };
    };
    getOrdersByOrderId: {
        parameters: {
            query: {
                /**
                 * @description リクエスター 配車依頼ユニークID(カンマ区切りで指定。一度に取得できるのは30件が最大。)<br/>- t_order.requester_order_id
                 * @example 1,2,3,4,5,6,7,8,9
                 */
                order_ids: components["schemas"]["orderId"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrder"][];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401UnAuthorized"];
            404: components["responses"]["404NotFound"];
            409: components["responses"]["409Conflict"];
            500: components["responses"]["500InternalServerError"];
        };
    };
    getOrderByOrderId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description リクエスター 配車依頼ユニークID<br/>- t_order.requester_order_id
                 * @example 1
                 */
                order_id: components["schemas"]["orderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrder"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401UnAuthorized"];
            404: components["responses"]["404NotFound"];
            409: components["responses"]["409Conflict"];
            500: components["responses"]["500InternalServerError"];
        };
    };
    deleteOrderByOrderId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description リクエスター 配車依頼ユニークID<br/>- t_order.requester_order_id
                 * @example 1
                 */
                order_id: components["schemas"]["orderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteOrder"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401UnAuthorized"];
            404: components["responses"]["404NotFound"];
            409: components["responses"]["409Conflict"];
            500: components["responses"]["500InternalServerError"];
        };
    };
}
